//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnzamtechWS
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiaSP
    {
        public int MaGia { get; set; }
        public int MaSP { get; set; }
        public int MaNV { get; set; }
        public double GiaSP1 { get; set; }
        public System.DateTime NgayTao { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
