//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnzamtechWS
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhapHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NhapHang()
        {
            this.CtNhapHangs = new HashSet<CtNhapHang>();
        }
    
        public int MaPNH { get; set; }
        public int NguoiNhap { get; set; }
        public int MaNXS { get; set; }
        public System.DateTime NgayNhap { get; set; }
        public System.DateTime NgayChinhSua { get; set; }
        public double TongGia { get; set; }
        public int TrangThai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CtNhapHang> CtNhapHangs { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        public virtual NhaSanXuat NhaSanXuat { get; set; }
    }
}
