//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnzamtechWS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Anh
    {
        public int MaAnh { get; set; }
        public int MaLA { get; set; }
        public int MaDMA { get; set; }
        public string TenAnh { get; set; }
        public string Tag { get; set; }
        public string Path { get; set; }
        public int TrangThai { get; set; }
    
        public virtual DanhMucAnh DanhMucAnh { get; set; }
        public virtual LoaiAnh LoaiAnh { get; set; }
    }
}
