//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnzamtechWS
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaiViet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BaiViet()
        {
            this.Tags = new HashSet<Tag>();
        }
    
        public int MaBV { get; set; }
        public int MaDMA { get; set; }
        public int MaNV { get; set; }
        public string TenBV { get; set; }
        public System.DateTime NgayDang { get; set; }
        public int MaDMBV { get; set; }
        public string MoTa { get; set; }
        public string NoiDung { get; set; }
        public string LinkFB { get; set; }
        public int TrangThai { get; set; }
    
        public virtual DanhMucAnh DanhMucAnh { get; set; }
        public virtual DanhMucBaiViet DanhMucBaiViet { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tag> Tags { get; set; }
    }
}
