//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnzamtechWS
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiaiPhap
    {
        public int MaGP { get; set; }
        public int MaDM { get; set; }
        public int MaDMA { get; set; }
        public string TenGP { get; set; }
        public string NoiDung { get; set; }
    
        public virtual DanhMuc DanhMuc { get; set; }
        public virtual DanhMucAnh DanhMucAnh { get; set; }
    }
}
