//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnzamtechWS
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.CtDonHangs = new HashSet<CtDonHang>();
            this.CtNhapHangs = new HashSet<CtNhapHang>();
            this.GiaSPs = new HashSet<GiaSP>();
        }
    
        public int MaSP { get; set; }
        public Nullable<int> MaDMA { get; set; }
        public int MaDMC { get; set; }
        public string TenSP { get; set; }
        public string MoTa { get; set; }
        public string Tag { get; set; }
        public string ChiTienSP { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public System.DateTime NgayTao { get; set; }
        public Nullable<System.DateTime> NgaySua { get; set; }
        public Nullable<int> SoNguoiTruyCap { get; set; }
        public int TrangThai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CtDonHang> CtDonHangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CtNhapHang> CtNhapHangs { get; set; }
        public virtual DanhMucAnh DanhMucAnh { get; set; }
        public virtual DanhMucCon DanhMucCon { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GiaSP> GiaSPs { get; set; }
    }
}
