//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnzamtechWS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongSo
    {
        public int MaTS { get; set; }
        public string TenTS { get; set; }
        public string Value { get; set; }
        public string Text { get; set; }
    }
}
